# [START runtime]
runtime: nodejs8
handlers:
  - url: /
    static_files: dist/resume-stephen/index.html
    upload: dist/resume-stephen/index.html
  - url: /
    static_dir: dist/resume-stephen
manual_scaling:
  instances: 1
# [END runtime]
